### ISSUE TITLE
Improve navbar

### ISSUE THREAD

**Issue by hazadus** [hazadus/nuxt-trello-board#10]
**Build more Trello-like navbar.**

## ToDos

- [ ] add search button
- [ ] add help button (context help💡)
- [x] listbox with user's boards
- [x] drop-down user menu
- [x] adjust menu colors (when not logged in)

## References 

- [Building a dropdown menu with Headless UI](https://tallpad.com/series/headlessui/lessons/building-a-dropdown-menu)
- [Create A Trello panel clone With Tailwind CSS Like A Pro With The Help Of These 6 Tips](https://www.tailwindcsscomponent.com/trello-panel-clone)
- [TailwindCSS - Trello Kanban](https://tallpad.com/series/trello-kanboard/lessons/tailwindcss-trello-kanban)
	- [Adding HeadlessUI dropdown menus](https://tallpad.com/series/trello-kanboard/lessons/adding-headlessui-dropdown-menus-trello-kanban)
- [Headless UI Listbox reusable vue component](https://tallpad.com/series/headlessui/lessons/headless-ui-listbox-reusable-vue-component)

**Comment by hazadus** [comment]
![image](https://github.com/hazadus/nuxt-trello-board/assets/6420045/310e9672-9119-4850-9189-4e4178badfbf)
