### ISSUE TITLE
User's boards page

### ISSUE THREAD

**Issue by hazadus** [hazadus/nuxt-trello-board#12]
**Page to view all existing user's boards and "New board" button**

## ToDos

- [x] List of all user's boards
- [x] "Create new board" button with popover
- [x] add `user` field to task, column, board
- [x] auto-add user id to tasks, columns, boards when created
- [x] only allow `user`s to get/put/delete their own tasks/columns/boards 

## References

- [Creating the board list - Trello Kanban](https://tallpad.com/series/trello-kanboard/lessons/creating-the-board-list-trello-kanban)
- [Popover form using HeadlessUI, TailwindCSS and InertiaJS - Trello Kanban](https://tallpad.com/series/trello-kanboard/lessons/popover-form-using-headlessui-tailwindcss-and-inertiajs-trello-kanban)
