### ISSUE TITLE
Detail board view page

### ISSUE THREAD

**Issue by hazadus** [hazadus/nuxt-trello-board#17]
## ToDos

- [x] create route `/boards/<id>`
- [x] create basic `/boards/` page
- [x] board title
- [x] editable board title
