### ISSUE TITLE
Push updates via SSE

### ISSUE THREAD

**Issue by hazadus** [hazadus/nuxt-trello-board#18]
Send notifications on DB updates from server to frontend using SSE.

## ToDos

- [x] create `/api/sse` endpoint
- [ ] define SSE data shape (interface)
- [ ] wire up frontend - update stores on corresponding events
- [ ] investigate into  HTTP/2 for SSE endpoint ...
- [ ] merge `main` into `18-updates-via-sse`!

## References

- https://valberg.dk/django-sse-postgresql-listen-notify.html#hooking-up-the-frontend

**Comment by hazadus** [comment]
```typescript
// ~/server/api/sse.ts
export default defineEventHandler(async (event) => {
  if (!process.dev) return { disabled: true }

  // Enable SSE endpoint
  setHeader(event, 'cache-control', 'no-cache')
  setHeader(event, 'connection', 'keep-alive')
  setHeader(event, 'content-type', 'text/event-stream')
  setResponseStatus(event, 200)

  let counter = 0

  const sendEvent = (data: any) => {
    event.node.res.write(`id: ${++counter}\n`);
    event.node.res.write(`data: ${JSON.stringify(data)}\n\n`);
  }

  myHooks.hook('sse:event', sendEvent)

  // Let the connection opened
  event._handled = true;
})
```
https://gist.github.com/Atinux/05836469acca9649fa2b9e865df898a2
