### ISSUE TITLE
Slideover board menu

### ISSUE THREAD

**Issue by hazadus** [hazadus/nuxt-trello-board#19]
## ToDos

- [x] `...` button with options slideover: menu - add description; change background; close board (consider soft-delete)
	- [x] [Building a slide-over dialog component with HeadlessUI and VueJS](https://tallpad.com/series/headlessui/lessons/building-a-slide-over-dialog-component-with-headlessui-and-vuejs)
- [x] pass `Board` as a prop to slideover
