### ISSUE TITLE
Implement MVP and 🚀 deploy

### ISSUE THREAD

**Issue by hazadus** [hazadus/nuxt-trello-board#22]
What I need to implement before first deploy.

## ToDos

- [x] #25
- [x] #26
- [x] #29
- [x] #31
- [x] Adjust styling of header menu and login/signup form colors
- [x] #33
- [x] Translate all text to russian
- [x] Fix z-index issues
- [x] #35
- [x] Remove unused buttons from navbar
- [x] 🐳 Docker configuration
- [x] Create favicon
- [x] Implement dropdown in navbar in mobile mode
- [x] Check UI in mobile mode
- [x] ⚡️Deploy!
