### ISSUE TITLE
Slideover board menu – actions

### ISSUE THREAD

**Issue by hazadus** [hazadus/nuxt-trello-board#23]
Implement actions inside board's slideover menu.

## ToDos

- [ ] "hide completed" option checkbox
- [ ] implement inline description editor
- [ ] `/boards/` `DELETE` endpoint (consider soft-delete)
- [ ] "Delete board" button

## Fix later

- [ ] leave transition on slideover does not work ([docs](https://headlessui.com/vue/transition))

**Comment by hazadus** [comment]
![image](https://github.com/hazadus/nuxt-trello-board/assets/6420045/331ef961-d3e1-4055-b314-496b6161cd86)
