### ISSUE TITLE
Set `user` property for new Columns, Tasks

### ISSUE THREAD

**Issue by hazadus** [hazadus/nuxt-trello-board#26]
# ToDos

- [x] make `user` field required in DB schemas
- [x] validate `user` field in `validation.ts` - 💡 we do not pass `user` from frontend to API, so no need to validate it there!
- [x] fill `user` fields in APIs
