### ISSUE TITLE
Modal task editor

### ISSUE THREAD

**Issue by hazadus** [hazadus/nuxt-trello-board#3]
- 💡 Modal "window" to edit all task data
	- [Edit card in HeadlessUI and InertiaJS modal - Trello Kanban](https://tallpad.com/series/trello-kanboard/lessons/edit-card-in-headlessui-and-inertiajs-modal-trello-kanban)

# ToDos

- [ ] move card to another board/column
- [ ] auto-resize text inputs
- [x] edit card title
- [x] add description to the card

**Comment by hazadus** [comment]
![image](https://github.com/hazadus/nuxt-trello-board/assets/6420045/3233b08b-a709-45fb-bfdf-8037163f992f)
![image](https://github.com/hazadus/nuxt-trello-board/assets/6420045/dc355d28-595c-4ce8-8e53-b588ca6b63ec)
![image](https://github.com/hazadus/nuxt-trello-board/assets/6420045/74e2a43f-4721-43f9-97b1-9661e7c7b8e4)
