### ISSUE TITLE
Allow to create new boards

### ISSUE THREAD

**Issue by hazadus** [hazadus/nuxt-trello-board#31]
## ToDos

- [x] `/boards` `POST` endpoint
- [x] add create method to `boardStore`
- [x] wire up frontend
