### ISSUE TITLE
🎈 Prep for presentation

### ISSUE THREAD

**Issue by hazadus** [hazadus/nuxt-trello-board#37]
Complete these features before showing project to friends.

## ToDos

- App index page
     - [x] Replace demo text with real project description
- Navbar
    - [x] User menu - disable not implemented menu items
    - [x] #10 
    - [x] Search bar (modal)
        - [x] Fix 🐞 `Uncaught TypeError: resultsRefs.value[selectedIndex.value] is undefined`
        - [x] Show icons (📎, star)
- Board
    - [x] #3 
   - [x]     #23 - "hide completed" option checkbox
   - [x] Show number of hidden completed cards in the column
- [x] Table view
    - [x] allow filtering and sorting: favorites, completed, etc.
- Cards
    - [ ] 📆 Add `dueDate` to cards
- #38 
    - [x] #40
    - [ ] 🙎‍♂️ Change profile image
- [x] "Contact" page: add info about the author 
- CI/CD
    - [x] Install Sentry
    - [x] Install Umami tracker 
    - [x] Auto-deploy with GitHub Actions
    - [ ] Config SSL using Nuxt
    - [ ] Log Umami events
 
## Complete Project

- [ ] Files page - show card title if file attached to card

## References

- https://vueuse.org/core/useFileDialog/
- https://github.com/ReaganM02/Nuxt3-Upload-Multiple-Files-To-MongoDB/blob/master/app.vue
- https://github.com/BayBreezy/nuxt-3-server-api/blob/main/pages/index.vue
- https://github.com/HC200ok/vue3-easy-data-table
