### ISSUE TITLE
Upload files

### ISSUE THREAD

**Issue by hazadus** [hazadus/nuxt-trello-board#38]
## ToDos

- [x] Protect "Files" page from anonymous users
- [x] Add "Files" page to dropdown menu in navbar (user or boards menu?)
- [x] Allow to delete files
- [x] Figure out problem with cyrillic letters in file names

## References

- https://github.com/ReaganM02/Nuxt3-Upload-Multiple-Files-To-MongoDB/tree/master
- https://github.com/expressjs/multer
- [How to Handle File Uploads on the Back End in Node.js and Nuxt](https://www.freecodecamp.org/news/handle-file-uploads-on-the-backend-in-node-js-nuxt/)
- [formidable](https://github.com/node-formidable/formidable/tree/master)
