### ISSUE TITLE
Use MongoDB as data storage

### ISSUE THREAD

**Issue by hazadus** [hazadus/nuxt-trello-board#4]
Try using MongoDB as backend DB for this project.

## ToDos

- [x] add MongoDB service to Docker Compose
- [x] add Mongoose to the project
- [x] connect to MongoDB service on backend
- [x] create API endpoints (just sketches for now)
- [x] create schema for tasks
- [x] create GET/POST/PUT/DELETE endpoints for Tasks with validation
- [x] create schema for columns
- [x] create GET/POST/PUT/DELETE endpoints for Columns with validation
- [x] add `{ timestamps: true }` in schemas
- [x] consume endpoints on the frontend
- [x] handle tasks drag and drop - save state in MongoDB
- [x] create `Board` model with `title` and `columns`
- [x] create`PUT` endpoint for boards + `boardStore`
- [x] handle columns drag and drop - save board state in MongoDB

## References

- https://www.youtube.com/watch?v=1uWHDdcDZWw
