### ISSUE TITLE
📎 Attach files to cards

### ISSUE THREAD

**Issue by hazadus** [hazadus/nuxt-trello-board#40]
## ToDos

- [x] add `IFile` array to `ITask`
- [x] add "Attach" button and list of attached files to `BoardTaskCardModal`
- [x] In `/uploads` `DELETE` endpoint, remove file from `ITask` `attachedFiles` array, if necessary.
- [x] refactor `FileItem` - small and large variants
- [x] add 📎 icon to cards
