### ISSUE TITLE
Implement simple auth

### ISSUE THREAD

**Issue by hazadus** [hazadus/nuxt-trello-board#5]
**Implement simple authentication in the app.**

## ToDos

- [x] `User` DB schema and validation
- [x] password hashing and salting
- [x] `/api/users/` - `POST` - create user endpoint
- [x] `AuthToken` schema
- [x] `/api/users/login` - `POST` - create AuthTokens
- [x] `authStore.initializeStore()`
- [x] `authStore.logIn()`
- [x] create server middleware to check auth token in `event.req.headers.authorization`
- [x] put auth token in headers: `Authentication: TOKEN`
- [x] implement user menu dropdown (hide when not authorized)
- [x] login page
- [x] `/api/users/logout` - logout enpoint (delete auth token from DB).
- [x] `authStore.logOut()` - reset token and user in storage

## References

- https://www.youtube.com/watch?v=hl6qvexLohM
- [How to Hash and Verify a Password in Node.js With bcrypt](https://www.makeuseof.com/nodejs-bcrypt-hash-verify-salt-password/)
- [bcrypt on npm](https://www.npmjs.com/package/bcrypt)
