### ISSUE TITLE
Allow to work with multiple boards

### ISSUE THREAD

**Issue by hazadus** [hazadus/nuxt-trello-board#6]
## ToDos

- [x] allow to rename board existing
- [x] show board title above the board and in window title
- [x] create`POST` endpoint for boards - allow to create new boards
