### ISSUE TITLE
Various todos / 💡 Ideas

### ISSUE THREAD

**Issue by hazadus** [hazadus/nuxt-trello-board#8]
## ToDos

- [ ] try enabling https in Nuxt config https://nuxt.com/docs/api/configuration/nuxt-config#https
- [ ] General tailwind stuff https://tallpad.com/series/tailwind
- [ ] Spinner button https://tallpad.com/series/vuejs-misc/lessons/vuejs-loading-button-with-tailwindcss
- [ ] Async combo box https://tallpad.com/series/vuejs-misc/lessons/vue-async-combobox-component
- [ ] use https://date-fns.org to format dates with `formatDistanceToNow`
- [ ] change font for task cards https://www.cufonfonts.com/font/menlo
- [ ] Use appConfig for app title  https://nuxt.com/docs/getting-started/configuration#runtimeconfig-vs-appconfig
- [ ] add confirmation window on task delete action
- [ ] handle task card cloning with `alt` key: create new document in DB for cloned cards. See Sortable.js docs on how to do it.
- [ ] focus reset from task after toggling completed, favorite status.
- [ ] help page or modal popup
- [ ] keyboard shortcuts (also mentioned in the menus) for common operations
- [x] Search modal https://tallpad.com/series/search-modal-dialog-with-headlessui-and-tailwindcss
- [x] text area with auto resize https://tallpad.com/series/vuejs-misc/lessons/building-a-vue-js-textarea-autoresize-component
- [x] Config prettier https://tallpad.com/series/tiny-tips/lessons/install-prettier-and-enforce-it-in-your-projects
- [x] add error page
- [x] add navbar
- [x] `  devtools: { enabled: true },`

## Ideas

- 💡 Blog section – news about updates
- 💡 "Soft" delete
- 💡 Tags for tasks
- 💡 Comments for tasks
- 💡 Image attachments
- 💡 File attachments
- 💡 Zoom board
